#!/usr/bin/env python
from misc.utility.scons_hints import *

Import('env')
Import("env_modules")

env_my_module = env_modules.Clone()

env_my_module.add_source_files(env.modules_sources, "*.cpp") # Add all cpp files to the build